# Funciones universales

En esta lección vamos a ver algunas de las funciones universales. Se llaman así porque sirven para aplicar funciones matemáticas comunes en los elementos.


Podemos encontrar:

* Operaciones matemáticas
* Operaciones trigonométricas
* Operaciones comparativas
* Operaciones flotantes
* Operaciones de intercambio de bits

[En la documentación oficial](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs) encontraréis el listado completo con ejemplos de uso, vamos a practicar las más utilizadas.

## Matemáticas

In [1]:
import numpy as np

# arrays de prueba
arr_1 = np.arange(1,6)
arr_2 = np.array([-3,7,3,13,0])

In [2]:
# suma
np.add(arr_1, arr_2)

array([-2,  9,  6, 17,  5])

In [3]:
# resta
np.subtract(arr_2, arr_1)

array([-4,  5,  0,  9, -5])

In [4]:
# raiz cuadrada
np.sqrt(arr_1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [5]:
# potencia
np.power(arr_1, 2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [6]:
# signo
np.sign(arr_1)

array([1, 1, 1, 1, 1])

## Trigonométricas

In [ ]:
# seno
np.sin(arr_1)

In [ ]:
# coseno
np.cos(arr_1)

In [ ]:
# tangente
np.tan(arr_1)

In [ ]:
# grados a radianes
np.deg2rad(arr_1)

In [ ]:
# radianes a grados
np.rad2deg(arr_1)

## Comparativas

In [8]:
# máximo
np.maximum(arr_1, arr_2)

array([ 1,  7,  3, 13,  5])

In [9]:
# mínimo
np.minimum(arr_1, arr_2)

array([-3,  2,  3,  4,  0])

In [10]:
# igual que
np.equal(arr_1, arr_2)

array([False, False,  True, False, False])

In [11]:
# mayor que
np.greater(arr_1, arr_2)

array([ True, False, False, False,  True])

## Flotantes

In [ ]:
# tercer array de prueba
arr_3 = np.array([3.14, 2.57, -6.4, 0.47, 5.5])

In [ ]:
# valor absoluto
np.fabs(arr_3)

In [ ]:
# techo (redondeo entero al alza)
np.ceil(arr_3)

In [ ]:
# suelo (redondeo entero a la baja)
np.floor(arr_3)